ase_args:
  format: extxyz
batch_size: 4
chemical_symbols:
- C
- O
- Pt
dataset: ase
dataset_file_name: /users/40247882/repository/GDPy/examples/expedition/online/nequip/aqueous/surf22-fixed/init/t0/m0/dataset.xyz
dataset_seed: 4
l_max: 2
loss_coeffs:
  forces: 1.0
  total_energy:
  - 3.0
  - L1Loss
max_epochs: 500
n_train: 14
n_val: 2
nonlinearity_type: gate
num_basis: 8
num_features: 32
optimizer_name: Adam
parity: true
r_max: 6.0
root: /users/40247882/repository/GDPy/examples/expedition/online/nequip/aqueous/surf22-fixed/init/t0/m0
run_name: auto
seed: 3877
wandb: false
